config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root to: 'users/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users
  resources :users, only: [:index, :show]
  resources :rewards
  resources :goals

  resources :treats
  resources :marks
  # Defines the root path route ("/")
  # root "posts#index"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener" 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/complete.rb
class Complete < ApplicationRecord
  belongs_to :user
  belongs_to :reward
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :user
  belongs_to :treat
end

app/models/new_goal.rb
class NewGoal < ApplicationRecord
  belongs_to :user
  belongs_to :reward
end

app/models/new_reward.rb
class NewReward < ApplicationRecord
  belongs_to :user
  has_many :goals, dependent: :destroy
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :user
end

app/models/treat.rb
class Treat < ApplicationRecord
  belongs_to :user

  has_many :marks, dependent: :destroy
  accepts_nested_attributes_for :marks, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :rewards, dependent: :destroy
  has_many :goals, dependent: :destroy

  has_many :treats, dependent: :destroy
  has_many :marks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    # user_path(resource)
    # rewards_path(resource)
    treats_path(resource)
  end

  def after_sign_up_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    # 招待用パラメータ
    devise_parameter_sanitizer.permit(:invite) do |u|
      u.permit(:email, :treat_id)
    end
    
    # 招待を承認する際のパラメータ
    devise_parameter_sanitizer.permit(:accept_invitation) do |u|
      u.permit(:password, :password_confirmation, :invitation_token, :name, :treat_id)
    end
  end
end

app/controllers/completes_controller.rb
class CompletesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: %i[edit update destroy]

  def index
    @goals = Goal.order(id: :asc).page(params[:page]).per(3)
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def new
    @goal = current_user.goals.new
  end

  def edit
  end

  def create
    @goal = current_user.goals.new(goal_params)

    if @goal.save
      redirect_to goals_path, notice: '目標の登録に成功！'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @goal.update(goal_params)
      flash.now.notice = '目標の編集に成功！'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @goal.destroy

    redirect_to goals_path, notice: '目標の削除に成功！'
  end

  private

  def goal_params
    params.require(:goal).permit(:content ,:progress)
  end

  def set_goal
    @goal = current_user.goals.find(params[:id])
  end
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  before_action :set_mark, only: %i[edit update]

  def index
  end

  def show
    @mark = Mark.find(params[:id])
  end

  def new
  end

  def edit
  end

  def update
    if @mark.update(mark_params)
      flash.now.notice = '目標の編集に成功！'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def mark_params
    params.require(:mark).permit(:content ,:progress)
  end

  def set_mark
    @mark = current_user.marks.find(params[:id])
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :set_reward, only: %i[edit update destroy]

  def index
    @rewards = Reward.order(completiondate: :asc).page(params[:page]).per(3)
  end

  def show
    @reward = Reward.find(params[:id])
  end

  def new
    @reward = current_user.rewards.new
  end

  def edit
  end

  def create
    @reward = current_user.rewards.new(reward_params)

    if @reward.save
      redirect_to rewards_path, notice: 'ご褒美の登録に成功！'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @reward.update(reward_params)
      flash.now.notice = 'ご褒美の編集に成功！'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @reward.destroy

    redirect_to rewards_path, notice: 'ご褒美の削除に成功！'
  end

  private

  def reward_params
    params.require(:reward).permit(:completiondate ,:content ,:location)
  end

  def set_reward
    @reward = current_user.rewards.find(params[:id])
  end
end

app/controllers/treats_controller.rb
class TreatsController < ApplicationController
  before_action :set_treat, only: %i[edit update destroy]

  def index
    @treats = Treat.order(completiondate: :asc).page(params[:page]).per(3)
  end

  def show
    @treat = Treat.find(params[:id])
    @marks = @treat.marks
  end

  def new
    @treat = current_user.treats.new
    @treat.marks.build
  end

  def edit
  end

  def create
    @treat = current_user.treats.new(treat_and_mark_params)
    @treat.marks.each { |mark| mark.user_id = current_user.id }

    if @treat.save
      redirect_to @treat, notice: 'ご褒美の登録に成功！'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @treat.update(treat_params)
      flash.now.notice = 'ご褒美の編集に成功！'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @treat.destroy

    redirect_to treats_path, notice: 'ご褒美の削除に成功！'
  end

  private

  def treat_params
    params.require(:treat).permit(:completiondate ,:content ,:location)
  end

  def set_treat
    @treat = current_user.treats.find(params[:id])
  end

  def treat_and_mark_params
    params.require(:treat).permit(:completiondate ,:content ,:location, marks_attributes: %i[content progress])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(id: :asc).page(params[:page]).per(3)  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/completes_helper.rb
module CompletesHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/treats_helper.rb
module TreatsHelper
end

app/views/completes/edit.html.erb
<h1>Completes#edit</h1>
<p>Find me in app/views/completes/edit.html.erb</p>

app/views/completes/index.html.erb
<h1>Completes#index</h1>
<p>Find me in app/views/completes/index.html.erb</p>

app/views/completes/new.html.erb
<h1>Completes#new</h1>
<p>Find me in app/views/completes/new.html.erb</p>

app/views/completes/show.html.erb
<h1>Completes#show</h1>
<p>Find me in app/views/completes/show.html.erb</p>

app/views/goals/_form.html.erb
<%= turbo_frame_tag goal do %>
  <%= bootstrap_form_with(model: goal, data: { action: "turbo:submit-end->modal#close" }) do |form| %>
    <%= form.text_area :content %>
    <%= form.number_field :progress %>
    <%= form.submit %>
  <% end %>
<% end %>

app/views/goals/_goal.html.erb
<%= turbo_frame_tag goal do %>
  <p style="color: green"><%= notice %></p>
  目標：<%= goal.content %>
  <br />
  進捗率：<%= goal.progress %>
  <%= link_to "編集", edit_goal_path(goal), class: "btn btn-sm btn-outline-primary me-2", data: { turbo_frame: "modal"} %>
<% end %>

app/views/goals/edit.html.erb
<%= render "modal", title: "目標の編集" do %>
  <%= render "form", goal: @goal %>
<% end %>

app/views/goals/index.html.erb
<% @goals.each do |goal| %>
  作成者：<%= goal.user.email %>
  <br />
  id：<%= goal.id %>
  目標：<%= goal.content %>
  進捗率：<%= goal.progress %>
  <%= link_to "編集", edit_goal_path(goal) %>
  <br />
  <br />
<% end %>

<%= paginate @goals %>

<%= link_to "新規作成", new_goal_path %>

app/views/goals/new.html.erb
<%= render "form", goal: @goal %>

app/views/goals/show.html.erb
<div id='goal'>
  <%= render @goal %>
</div>

app/views/goals/update.turbo_stream.erb
<%= turbo_stream.update 'goal', @goal %>

app/views/marks/_form.html.erb
<%= turbo_frame_tag mark do %>
  <%= bootstrap_form_with(model: mark, data: { action: "turbo:submit-end->modal#close" }) do |form| %>
    <%= form.text_area :content %>
    <%= form.number_field :progress %>
    <%= form.submit %>
  <% end %>
<% end %>

app/views/marks/_mark.html.erb
<%= turbo_frame_tag mark do %>
  <p style="color: green"><%= notice %></p>
  目標：<%= mark.content %>
  進捗率：<%= mark.progress %>%
  <%= link_to "編集", edit_mark_path(mark), class: "btn btn-sm btn-outline-primary me-2", data: { turbo_frame: "modal"} %>
<% end %>

app/views/marks/edit.html.erb
<%= render "modal", title: "目標の編集" do %>
  <%= render "form", mark: @mark %>
<% end %>

app/views/marks/index.html.erb
<h1>Marks#index</h1>
<p>Find me in app/views/marks/index.html.erb</p>

app/views/marks/new.html.erb
<h1>Marks#new</h1>
<p>Find me in app/views/marks/new.html.erb</p>

app/views/marks/show.html.erb
<h1>Marks#show</h1>
<p>Find me in app/views/marks/show.html.erb</p>

<%= @mark.content %>
<%= @mark.progress %>

app/views/marks/update.turbo_stream.erb
<%= turbo_stream.update dom_id(@mark), @mark %>

app/views/rewards/_form.html.erb
<%= turbo_frame_tag reward do %>
  <%= bootstrap_form_with(model: reward, data: { action: "turbo:submit-end->modal#close" }) do |form| %>
      <%= form.date_field :completiondate, value: reward.completiondate %>
      <%= form.text_area :location %>
      <%= form.text_area :content %>
      <%= form.submit %>
  <% end %>
<% end %>

app/views/rewards/_reward.html.erb
<%= turbo_frame_tag reward do %>
  <p style="color: green"><%= notice %></p>
  <%= reward.completiondate %>に
  <%= reward.location %>で
  <%= reward.content %>する
  <%= link_to "編集", edit_reward_path(reward), class: "btn btn-sm btn-outline-primary me-2", data: { turbo_frame: "modal"} %>
<% end %>
<%= button_to "削除", reward, method: :delete, class: "btn btn-sm btn-outline-danger", data: { turbo_confirm: "削除しますか？" } %>

app/views/rewards/edit.html.erb
<%= render "modal", title: "ご褒美の編集" do %>
  <%= render "form", reward: @reward %>
<% end %>

app/views/rewards/index.html.erb
<p style="color: green"><%= notice %></p>

<% @rewards.each do |reward| %>
  <%= turbo_frame_tag reward do %>
    作成者：<%= reward.user.email %>
    <br />
    <%= reward.completiondate %>に　
    <%= link_to reward.location, reward_path(reward.id), data: { turbo: false } %>で　
    <%= reward.content %>する
    <br />
    <br />
  <% end %>
<% end %>

<%= paginate @rewards %>
<br />
<%= link_to "新規作成", new_reward_path %>

app/views/rewards/new.html.erb
<%= render "form", reward: @reward %>

app/views/rewards/show.html.erb
<div id='reward'>
  <%= render @reward %>
</div>

app/views/rewards/update.turbo_stream.erb
<%= turbo_stream.update 'reward', @reward %>

app/views/treats/_form.html.erb
 <%= turbo_frame_tag treat do %>
  <%= bootstrap_form_with(model: treat, data: { action: "turbo:submit-end->modal#close" }) do |form| %>
      <%= form.date_field :completiondate, value: treat.completiondate %>
      <%= form.text_area :location %>
      <%= form.text_area :content %>
      <%= form.submit %>
  <% end %>
<% end %>

app/views/treats/_treat.html.erb
<%= turbo_frame_tag treat do %>
  <p style="color: green"><%= notice %></p>
  ご褒美：
  <%= treat.completiondate %>に　
  <%= treat.location %>で　
  <%= treat.content %>する
  <%= link_to "編集", edit_treat_path(treat), class: "btn btn-sm btn-outline-primary me-2", data: { turbo_frame: "modal"} %>
<% end %>
  <%= button_to "削除", treat, method: :delete, class: "btn btn-sm btn-outline-danger", data: { turbo_confirm: "削除しますか？" } %>
  

app/views/treats/edit.html.erb
<h1>Treats#edit</h1>
<%= render "modal", title: "ご褒美の編集" do %>
  <%= render "form", treat: @treat %>
<% end %>

app/views/treats/index.html.erb
<h1>Treats#index</h1>

<% @treats.each do |treat| %>
  <br />
  作成者：<%= treat.user.email %>
  <br />
  <%= treat.completiondate %>に　
  <%= link_to treat.location, treat_path(treat.id) %>で　
  <%= treat.content %>する　

  <% treat.marks.each do |mark| %>
    <% if treat.user_id == mark.user_id %>
      進捗率：<%= mark.progress %>%
    <% end %>
  <% end %>
  <br />
<% end %>

<%= paginate @treats %>
<br />
<%= link_to "新規作成", new_treat_path %>

app/views/treats/new.html.erb
<h1>Treats#new</h1>

<%= form_with(model: @treat) do |form| %>

  <% if @treat.errors.any? %>
    <div style="color: red">
    <ul>
      <% @treat.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
    </div>
  <% end %>

  <%= form.label :期日, style: "display: block" %>
  <%= form.date_field :completiondate, value: @treat.completiondate %>

  <%= form.label :場所, style: "display: block" %>
  <%= form.text_area :location %>

  <%= form.label :ご褒美, style: "display: block" %>
  <%= form.text_area :content %>

    <%= form.fields_for :marks do |mark_form| %>
      <%= mark_form.label :content, '目標', style: "display: block" %>
      <%= mark_form.text_area :content %>
  
      <%= mark_form.label :progress, '進捗率', style: "display: block" %>
      <%= mark_form.number_field :progress %>
    <% end %>

  <%= form.submit %>
<% end %>

app/views/treats/show.html.erb
<h1>Treats#show</h1>

<br />
<div id='treat'>
  <%= render @treat %>
</div>

<br /><br />

<% @marks.each do |mark| %>
  <div id="<%= dom_id(mark) %>">
    <%= render 'marks/mark', mark: mark %>
  </div>
<% end %>

app/views/treats/update.turbo_stream.erb
<%= turbo_stream.update 'treat', @treat %>